/* ============================================================
   Drum Dojo — content library
   Pattern string legend (per 16th/triplet step):
     X = accent   x = normal hit   o = ghost note   . = rest
   Sticking string: R / L / . (rest)
   Ornament string: f = flam   d = drag   z = buzz   . = none
   ============================================================ */

// Kit rows, top -> bottom (only rows present in a pattern are shown)
const ROWS=[
  {id:"crash",label:"Crash"},{id:"ride",label:"Ride"},{id:"openhat",label:"Open HH"},{id:"hat",label:"Hi-Hat"},
  {id:"tom1",label:"Tom 1"},{id:"tom2",label:"Tom 2"},{id:"snare",label:"Snare"},{id:"rim",label:"Cross-Stick"},
  {id:"floor",label:"Floor Tom"},{id:"kick",label:"Kick"}
];

const LIB={
groove:[
 {name:"Basic Rock Beat",style:"Rock",diff:1,meter:"4/4",bpm:90,sub:4,
  desc:"The foundation of modern drumming. Hi-hat on every 8th note, kick on 1 & 3, snare on 2 & 4.",
  tip:"Keep your hi-hat hand steady and relaxed — let it ride. The snare backbeat on 2 & 4 is the heartbeat of rock.",
  tracks:{hat:"x.x.x.x.x.x.x.x.",snare:"....x.......x...",kick:"x.......x......."}},
 {name:"Rock w/ 8th Kicks",style:"Rock",diff:2,meter:"4/4",bpm:95,sub:4,
  desc:"Adds a pushing kick on the '&' of 2 for forward drive.",
  tip:"That extra kick makes it groove instead of march. Land it tight with the hi-hat.",
  tracks:{hat:"x.x.x.x.x.x.x.x.",snare:"....x.......x...",kick:"x.....x.x.....x."}},
 {name:"Driving 8ths",style:"Rock",diff:2,meter:"4/4",bpm:120,sub:4,
  desc:"Busy kick under steady hats — energetic and propulsive.",
  tip:"A stamina builder. Keep the hats even while the kick drives underneath.",
  tracks:{hat:"x.x.x.x.x.x.x.x.",snare:"....x.......x...",kick:"x...x.x.x...x.x."}},
 {name:"Half-Time Groove",style:"Rock",diff:2,meter:"4/4",bpm:80,sub:4,
  desc:"Snare on beat 3 only — huge, spacious, modern feel.",
  tip:"Resist rushing — the space is the point. Count slowly and let beat 3 hit hard.",
  tracks:{hat:"x.x.x.x.x.x.x.x.",snare:"........x.......",kick:"x.......x...x..."}},
 {name:"Punk / Fast Rock",style:"Rock",diff:3,meter:"4/4",bpm:170,sub:4,
  desc:"Relentless 8th hats and a driving kick — pure energy.",
  tip:"Stay loose so you don't tense up at speed. Let the backbeat snap.",
  tracks:{hat:"x.x.x.x.x.x.x.x.",snare:"....x.......x...",kick:"x.x.x.x.x.x.x.x."}},
 {name:"Metal Double-Kick",style:"Rock",diff:4,meter:"4/4",bpm:150,sub:4,
  desc:"Steady 16th kick under crashing 8ths.",
  tip:"With a double pedal, alternate feet. Otherwise drop to 8th kicks and build up.",
  tracks:{crash:"x.x.x.x.x.x.x.x.",snare:"....x.......x...",kick:"xxxxxxxxxxxxxxxx"}},

 {name:"Four-on-the-Floor",style:"Pop / Dance",diff:2,meter:"4/4",bpm:122,sub:4,
  desc:"Disco/dance staple — kick on all four, open hat on the off-beats.",
  tip:"Bury the kick on every beat and let the open hat 'breathe' on the &s.",
  tracks:{openhat:"..x...x...x...x.",hat:"x...x...x...x...",snare:"....x.......x...",kick:"x...x...x...x..."}},
 {name:"Pop Groove",style:"Pop / Dance",diff:1,meter:"4/4",bpm:105,sub:4,
  desc:"Clean, radio-ready beat with a tight backbeat.",
  tip:"Consistency over flash. This beat fits the vast majority of pop songs.",
  tracks:{hat:"x.x.x.x.x.x.x.x.",snare:"....x.......x...",kick:"x.....x.x......."}},
 {name:"Motown Backbeat",style:"Pop / Dance",diff:2,meter:"4/4",bpm:128,sub:4,
  desc:"Snare on ALL four beats — the classic Motown/soul drive.",
  tip:"Heard on countless soul records. Keep the snare even and confident.",
  tracks:{hat:"x.x.x.x.x.x.x.x.",snare:"x...x...x...x...",kick:"x.......x......."}},

 {name:"Money Beat (Funk)",style:"Funk",diff:3,meter:"4/4",bpm:100,sub:4,
  desc:"Syncopated funk kick with light snare ghost notes.",
  tip:"Lock the kick syncopation against steady hats. Keep the ghost notes (small dots) whisper-quiet.",
  tracks:{hat:"x.x.x.x.x.x.x.x.",snare:"..o.X..o..o.X..o",kick:"x..x..x...x.x..."}},
 {name:"Funky Drummer",style:"Funk",diff:4,meter:"4/4",bpm:98,sub:4,
  desc:"Ghost-note funk inspired by Clyde Stubblefield — the most sampled beat in history.",
  tip:"The quiet ghost notes between the backbeats are everything. Accents pop, ghosts disappear.",
  tracks:{hat:"x.x.x.x.x.x.x.x.",snare:"..o.X..oo.X.o..X",kick:"x.....x.x......."}},
 {name:"16th Hi-Hat Funk",style:"Funk",diff:3,meter:"4/4",bpm:92,sub:4,
  desc:"Continuous 16th notes on the hats for a busy, bubbling pocket.",
  tip:"Alternate hands on the hats if needed. Lightly accent the downbeats 1-2-3-4.",
  tracks:{hat:"xxxxxxxxxxxxxxxx",snare:"....x.......x...",kick:"x..x..x...x....."}},

 {name:"Boom-Bap Hip-Hop",style:"Hip-Hop",diff:2,meter:"4/4",bpm:90,sub:4,
  desc:"Hard kick & snare with a laid-back, behind-the-beat feel.",
  tip:"Play slightly behind the click for that heavy, lazy pocket.",
  tracks:{hat:"x.x.x.x.x.x.x.x.",snare:"....x.......x...",kick:"x.x....x..x....."}},
 {name:"Trap Feel",style:"Hip-Hop",diff:3,meter:"4/4",bpm:140,sub:4,
  desc:"Half-time snare with rolling hat subdivisions.",
  tip:"Snare lands on beat 3 (half-time). Roll the hats fast and even.",
  tracks:{hat:"xxxxxxxxxxxxxxxx",snare:"........x.......",kick:"x.....x.....x..x"}},

 {name:"Shuffle (Triplet)",style:"Blues / Shuffle",diff:3,meter:"shuffle",bpm:100,sub:3,
  desc:"Bluesy triplet swing. Hats on the 1st & 3rd of each triplet.",
  tip:"Say 'tri-pl-et' — play on 'tri' and 'et', skip 'pl'. Snare on 2 & 4.",
  tracks:{hat:"x.xx.xx.xx.x",snare:"...x.....x..",kick:"x.....x....."}},
 {name:"12/8 Blues",style:"Blues / Shuffle",diff:2,meter:"12/8",bpm:60,sub:3,
  desc:"Slow blues with triplets rolling on the ride.",
  tip:"Let it breathe. Every beat is a triplet — keep them smooth and even.",
  tracks:{ride:"x.xx.xx.xx.x",snare:"...x.....x..",kick:"x.....x....."}},
 {name:"Half-Time Shuffle",style:"Blues / Shuffle",diff:5,meter:"shuffle",bpm:96,sub:3,
  desc:"The Purdie/Porcaro feel — ghosted triplet shuffle, big snare on 3.",
  tip:"Advanced. Ghost the extra snare triplets very quietly around the main backbeat on 3.",
  tracks:{hat:"x.xx.xx.xx.x",snare:".o.o.oX.o.o.",kick:"x.....x....."}},
 {name:"Train Beat (Country)",style:"Blues / Shuffle",diff:3,meter:"4/4",bpm:110,sub:4,
  desc:"Chugging snare 16ths with backbeat accents — the 'freight train' feel.",
  tip:"Play the chug as quiet ghost notes with accents on 2 & 4. Brushes sound great here.",
  tracks:{snare:"ooooXoooooooXooo",kick:"x.......x......."}},

 {name:"Jazz Swing",style:"Jazz / Latin",diff:4,meter:"swing",bpm:130,sub:3,
  desc:"Ride swing pattern with the hi-hat foot on 2 & 4.",
  tip:"The ride is the engine: 'ding, ding-da-ding'. Keep the hi-hat foot crisp on 2 & 4.",
  tracks:{ride:"x.xx.xx.xx.x",hat:"...x.....x..",kick:"x..........."}},
 {name:"Bossa Nova",style:"Jazz / Latin",diff:3,meter:"4/4",bpm:120,sub:4,
  desc:"Cross-stick clave over a steady kick and smooth hat 8ths.",
  tip:"The cross-stick plays the bossa clave. Keep the kick soft and constant underneath.",
  tracks:{hat:"x.x.x.x.x.x.x.x.",rim:"x..x..x...x.x...",kick:"x..x..x...x..x.."}},
 {name:"Samba",style:"Jazz / Latin",diff:4,meter:"4/4",bpm:100,sub:4,
  desc:"Surdo-style kick ostinato with a driving hat.",
  tip:"The kick 'two-feel' (weak-STRONG) is the heart of samba. Keep it bouncing.",
  tracks:{hat:"x.xxx.xxx.xxx.xx",rim:"..x..x.x..x..x.x",kick:"x..xx..xx..xx..x"}},
 {name:"Reggae One Drop",style:"Jazz / Latin",diff:2,meter:"4/4",bpm:80,sub:4,
  desc:"Kick AND snare together on beat 3 — nothing on beat 1.",
  tip:"Leaving beat 1 empty is the whole vibe. Let it drop on 3.",
  tracks:{hat:"x.x.x.x.x.x.x.x.",snare:"........x.......",kick:"........x......."}},
 {name:"Reggae Steppers",style:"Jazz / Latin",diff:2,meter:"4/4",bpm:78,sub:4,
  desc:"Four-on-the-floor kick under a one-drop cross-stick feel.",
  tip:"Steady kick on every beat 'steps' the groove forward.",
  tracks:{hat:"x.x.x.x.x.x.x.x.",rim:"........x.......",kick:"x...x...x...x..."}},
],

rudiment:[
 // SINGLES
 {name:"Single Stroke Roll",fam:"Singles",diff:1,meter:"16ths",bpm:80,sub:4,
  desc:"R L R L — the most fundamental rudiment.",
  tip:"Even volume, even spacing, both hands equal. Watch your weak hand match your strong hand.",
  hits:"xxxxxxxxxxxxxxxx",stick:"RLRLRLRLRLRLRLRL"},
 {name:"Single Stroke Four",fam:"Singles",diff:2,meter:"triplet",bpm:90,sub:3,
  desc:"Four fast singles resolving to an accent.",
  tip:"A burst of four even notes; accent the landing. Great for quick fills.",
  hits:"xxxxxxxxxxxX",stick:"RLRLRLRLRLRL"},
 {name:"Single Stroke Seven",fam:"Singles",diff:2,meter:"triplet",bpm:85,sub:3,
  desc:"Seven singles to an accent — a longer burst.",
  tip:"Keep all seven perfectly even before the accent. Alternate the starting hand each rep.",
  hits:"xxxxxxX.....",stick:"RLRLRLR....."},
 // ROLLS
 {name:"Double Stroke Roll",fam:"Rolls",diff:2,meter:"16ths",bpm:70,sub:4,
  desc:"R R L L — two bounces per hand.",
  tip:"Let the stick rebound for the 2nd hit — don't muscle it. Both strokes equal.",
  hits:"xxxxxxxxxxxxxxxx",stick:"RRLLRRLLRRLLRRLL"},
 {name:"Triple Stroke Roll",fam:"Rolls",diff:3,meter:"triplet",bpm:75,sub:3,
  desc:"R R R L L L — three strokes per hand.",
  tip:"Controlled bounce, three even notes per hand. Bridges doubles and the buzz roll.",
  hits:"xxxxxxxxxxxx",stick:"RRRLLLRRRLLL"},
 {name:"Buzz (Multiple Bounce) Roll",fam:"Rolls",diff:3,meter:"16ths",bpm:80,sub:4,
  desc:"Press each stroke for a sustained 'buzz'.",
  tip:"Push the stick into the head and let it buzz. Aim for a smooth, gapless sound.",
  hits:"xxxxxxxxxxxxxxxx",stick:"RLRLRLRLRLRLRLRL",orn:"zzzzzzzzzzzzzzzz"},
 {name:"Five Stroke Roll",fam:"Rolls",diff:2,meter:"16ths",bpm:80,sub:4,
  desc:"R R L L R — two doubles plus an accent.",
  tip:"Build the doubles smoothly into the accent, then start the next on the other hand.",
  hits:"xxxxX..xxxxX..",stick:"RRLLR..LLRRL.."},
 {name:"Seven Stroke Roll",fam:"Rolls",diff:3,meter:"16ths",bpm:80,sub:4,
  desc:"R R L L R R L — three doubles to an accent.",
  tip:"Keep the doubles even and let the accent ring. Alternate the lead hand each rep.",
  hits:"xxxxxxX.xxxxxxX.",stick:"RRLLRRL.LLRRLLR."},
 {name:"Nine Stroke Roll",fam:"Rolls",diff:3,meter:"16ths",bpm:78,sub:4,
  desc:"R R L L R R L L R — four doubles to an accent.",
  tip:"A staple of fills. Land the accent cleanly and reset for the next.",
  hits:"xxxxxxxxX.......",stick:"RRLLRRLLR......."},
 // DIDDLES
 {name:"Single Paradiddle",fam:"Diddles",diff:2,meter:"16ths",bpm:80,sub:4,
  desc:"R L R R  L R L L — the classic coordination builder.",
  tip:"Accent the FIRST note of each group. That accent is what makes paradiddles musical.",
  hits:"XxxxXxxxXxxxXxxx",stick:"RLRRLRLLRLRRLRLL"},
 {name:"Double Paradiddle",fam:"Diddles",diff:3,meter:"triplet",bpm:90,sub:3,
  desc:"R L R L R R  L R L R L L — six-note groups, perfect for triplets.",
  tip:"Naturally fits a triplet feel. Accent the first note of each six.",
  hits:"XxxxxxXxxxxx",stick:"RLRLRRLRLRLL"},
 {name:"Triple Paradiddle",fam:"Diddles",diff:3,meter:"16ths",bpm:80,sub:4,
  desc:"R L R L R L R R — eight-note groups before the diddle.",
  tip:"Longer single run before the diddle. Keep the accent on note one.",
  hits:"XxxxxxxxXxxxxxxx",stick:"RLRLRLRRLRLRLRLL"},
 {name:"Paradiddle-diddle",fam:"Diddles",diff:3,meter:"triplet",bpm:90,sub:3,
  desc:"R L R R L L — a single then two diddles; stays on one lead hand.",
  tip:"Because it doesn't alternate, it's a monster for around-the-kit fills.",
  hits:"XxxxxxXxxxxx",stick:"RLRRLLRLRRLL"},
 // FLAMS
 {name:"Flam",fam:"Flams",diff:2,meter:"8ths",bpm:70,sub:4,
  desc:"A grace note just before the main note — 'fl-AM'.",
  tip:"One stick low (quiet grace), one high (loud main). Should sound like one fat hit.",
  hits:"X.X.X.X.X.X.X.X.",stick:"R.L.R.L.R.L.R.L.",orn:"f.f.f.f.f.f.f.f."},
 {name:"Flam Accent",fam:"Flams",diff:3,meter:"triplet",bpm:80,sub:3,
  desc:"Flam + two taps in a triplet — 'FLAM-tap-tap'.",
  tip:"Flam on the accent, two clean singles after. Alternate the lead hand each triplet.",
  hits:"XxxXxxXxxXxx",stick:"RLRLRLRLRLRL",orn:"f..f..f..f.."},
 {name:"Flam Tap",fam:"Flams",diff:3,meter:"16ths",bpm:75,sub:4,
  desc:"Flam then a tap on the SAME hand — 'FLAM-tap'.",
  tip:"The tap uses the same hand that played the main flam note. Keep taps even.",
  hits:"XxXxXxXxXxXxXxXx",stick:"RRLLRRLLRRLLRRLL",orn:"f.f.f.f.f.f.f.f."},
 {name:"Flamacue",fam:"Flams",diff:4,meter:"16ths",bpm:75,sub:4,
  desc:"Flam, accent on the 2nd note, ending with a flam.",
  tip:"The 'cue' is the accent on note two. Famous, tricky, very rewarding.",
  hits:"XXxxX...XXxxX...",stick:"RLRLR...LRLRL...",orn:"f...f...f...f..."},
 {name:"Flam Paradiddle",fam:"Flams",diff:4,meter:"16ths",bpm:75,sub:4,
  desc:"A flam on the first note of each paradiddle.",
  tip:"Combine flam control with paradiddle motion. Flam leads, diddle finishes.",
  hits:"XxxxXxxxXxxxXxxx",stick:"RLRRLRLLRLRRLRLL",orn:"f...f...f...f..."},
 {name:"Swiss Army Triplet",fam:"Flams",diff:3,meter:"triplet",bpm:85,sub:3,
  desc:"Flam, then a quick double — 'FLAM-da-da' triplet.",
  tip:"A fill favorite. Flam on one, then R R (or L L) to finish the triplet.",
  hits:"XxxXxxXxxXxx",stick:"RRLLRRLLRRLL",orn:"f..f..f..f.."},
 {name:"Inverted Flam Tap",fam:"Flams",diff:4,meter:"16ths",bpm:75,sub:4,
  desc:"Flams on the inner notes — a flowing alternating flam pattern.",
  tip:"The flam falls on the 'and'. Smooth, rolling motion between the hands.",
  hits:"xXxXxXxXxXxXxXxX",stick:"RRLLRRLLRRLLRRLL",orn:".f.f.f.f.f.f.f.f"},
 {name:"Pataflafla",fam:"Flams",diff:5,meter:"16ths",bpm:72,sub:4,
  desc:"Flams on the outer notes of each four-note group.",
  tip:"Flam-note-note-flam. Two flams per group — great for hand independence.",
  hits:"XxxXXxxXXxxXXxxX",stick:"RLRLLRLRRLRLLRLR",orn:"f..ff..ff..ff..f"},
 // DRAGS
 {name:"Drag (Ruff)",fam:"Drags",diff:3,meter:"8ths",bpm:70,sub:4,
  desc:"Two quick grace notes before the main note.",
  tip:"The drag is two soft bounces leading into the main hit. Keep the graces quiet.",
  hits:"x.x.x.x.x.x.x.x.",stick:"R.L.R.L.R.L.R.L.",orn:"d.d.d.d.d.d.d.d."},
 {name:"Single Drag Tap",fam:"Drags",diff:3,meter:"8ths",bpm:75,sub:4,
  desc:"Drag + accented note, then a tap.",
  tip:"Drag into the accent, then one clean tap. Alternate the lead each group.",
  hits:"X.x.X.x.X.x.X.x.",stick:"R.L.L.R.R.L.L.R.",orn:"d...d...d...d..."},
 {name:"Double Drag Tap",fam:"Drags",diff:4,meter:"triplet",bpm:75,sub:3,
  desc:"Two drags leading into an accented tap.",
  tip:"Two drags in a row then the accent — keep the graces light, the accent strong.",
  hits:"x.X.x.x.X.x.",stick:"R.R.L.L.L.R.",orn:"d.d...d.d..."},
 {name:"Single Ratamacue",fam:"Drags",diff:4,meter:"triplet",bpm:80,sub:3,
  desc:"Drag + three notes with the accent on the last — 'ra-ta-ma-CUE'.",
  tip:"Drag into a triplet, accent the final note. Say 'ra-ta-ma-cue' as you play.",
  hits:"xxxXxxxX....",stick:"RLRLLRLR....",orn:"d...d......."},
],

fill:[
 {name:"Basic 4-Beat Fill",diff:1,meter:"16ths",bpm:90,sub:4,
  desc:"Snare → Tom 1 → Tom 2 → Floor across the bar in 16ths.",
  tip:"The most-used fill ever. End on the floor so you can crash on the next downbeat.",
  tracks:{snare:"xxxx............",tom1:"....xxxx........",tom2:"........xxxx....",floor:"............xxxx"}},
 {name:"Half-Bar Tom Fill",diff:2,meter:"16ths",bpm:95,sub:4,
  desc:"Groove for 2 beats, fill the last 2 down the toms.",
  tip:"Play time on 1-2, fall down the kit on 3-4. Practice re-entering the groove cleanly.",
  tracks:{hat:"x.x.x.x.........",snare:"....x...x.x.....",kick:"x.......x.......",tom1:"..........x.x...",floor:"..............xx"}},
 {name:"Triplet Tom Fill",diff:2,meter:"triplet",bpm:90,sub:3,
  desc:"Rolling triplets cascading down the drums.",
  tip:"Keep triplets even as you move down: snare, tom1, tom2, floor. Crash after.",
  tracks:{snare:"xxx.........",tom1:"...xxx......",tom2:"......xxx...",floor:".........xxx"}},
 {name:"Sextuplet Fill",diff:4,meter:"sextuplet",bpm:85,sub:6,
  desc:"Fast 16th-note triplets ripping down the toms.",
  tip:"Six notes per beat. Start slow! Even, controlled single strokes around the kit.",
  tracks:{snare:"xxxxxx..................",tom1:"......xxxxxx............",tom2:"............xxxxxx......",floor:"..................xxxxxx"}},
 {name:"Linear Funk Fill",diff:3,meter:"16ths",bpm:100,sub:4,
  desc:"No two limbs at once — kick, snare & toms weave together.",
  tip:"Linear = one note at a time. Say the limbs out loud slowly before speeding up.",
  tracks:{snare:"x..x..x..x..x..x",kick:".x..x..x..x..x..",tom1:"..x.....x.......",floor:"..........x..x.."}},
 {name:"Flam Fill",diff:3,meter:"16ths",bpm:88,sub:4,
  desc:"Accented flams moving around the toms.",
  tip:"Fat flams on each tom give the fill weight and punch. Keep grace notes quiet.",
  tracks:{snare:"X...X...........",tom1:"....X...X.......",tom2:"........X...X...",floor:"............X..X"}},
 {name:"Single-Stroke Cascade",diff:2,meter:"16ths",bpm:95,sub:4,
  desc:"Continuous singles flowing down snare → toms → floor.",
  tip:"Even, machine-steady single strokes. Let the pitch fall as you descend.",
  tracks:{snare:"xx..............",tom1:"..xx............",tom2:"....xxxx........",floor:"........xxxxxxxx"}},
 {name:"Buzz Build",diff:2,meter:"16ths",bpm:90,sub:4,
  desc:"A buzz-roll crescendo into a crash.",
  tip:"Start soft, swell louder across the bar, then explode on the crash.",
  tracks:{snare:"xxxxxxxxxxxxxxxx",crash:"...............X"}},
 {name:"Bonham Triplets",diff:4,meter:"triplet",bpm:100,sub:3,
  desc:"Hand-hand-foot triplets around the kit (Moby Dick style).",
  tip:"R L K, R L K — two hands then kick per triplet. Move the hands down the toms.",
  tracks:{snare:"xx.xx.......",tom1:"......xx....",floor:".........xx.",kick:"..x..x..x..x"}},
 {name:"Off-Beat Snare Fill",diff:3,meter:"16ths",bpm:96,sub:4,
  desc:"Syncopated snare hits with the kick filling the gaps.",
  tip:"Lands on the 'e' and 'a' — feels off-kilter and funky. Lock it to the metronome.",
  tracks:{snare:".x.x.x.x.x.x.x.x",kick:"x.x.x.x.x.x.x.x."}},
 {name:"Two-Beat Build",diff:2,meter:"16ths",bpm:94,sub:4,
  desc:"Groove for 2 beats, then a 16th snare-to-floor build.",
  tip:"Sets up a chorus nicely. Crescendo the build into the downbeat.",
  tracks:{hat:"x.x.x.x.........",snare:"....x...xxxxxxxx",kick:"x.......x.......",floor:"............xxxx"}},
 {name:"Crash Ending Fill",diff:2,meter:"16ths",bpm:90,sub:4,
  desc:"Tom roll resolving to a big crash + kick on '1'.",
  tip:"The payoff is the crash on the next downbeat (last cell). Hit it with the kick.",
  tracks:{snare:"xx......xx......",tom1:"..xx......xx....",floor:"....xx......xx..",crash:"...............X",kick:"...............x"}},
 {name:"Gospel 16th Chops",diff:5,meter:"16ths",bpm:88,sub:4,
  desc:"Busy snare/tom 16ths with ghost notes — gospel/fusion flavor.",
  tip:"Mix loud accents with whisper-quiet ghost notes. Dynamics make it sing.",
  tracks:{snare:"Xoox.ooXoox.ooXo",tom1:"....x......x....",floor:"..........x....."}},
 {name:"Tom Groove Fill",diff:2,meter:"16ths",bpm:100,sub:4,
  desc:"Keep the beat going on toms instead of stopping for a fill.",
  tip:"Play the groove but ride toms instead of hats — a seamless transition in and out.",
  tracks:{tom1:"x.x.x.x.x.x.x.x.",snare:"....x.......x...",kick:"x.....x.x......."}},
],
};

/* ===== SONGS (chain grooves + fills) ===== */
const SONGS=[
 {name:"Rock Anthem",bpm:112,desc:"Intro → verse → fill → chorus → fill. A classic arrangement.",
  parts:[
   {label:"Intro",ref:["groove","Basic Rock Beat"],bars:2},
   {label:"Verse",ref:["groove","Rock w/ 8th Kicks"],bars:4},
   {label:"Fill",ref:["fill","Basic 4-Beat Fill"],bars:1},
   {label:"Chorus",ref:["groove","Four-on-the-Floor"],bars:4},
   {label:"Fill",ref:["fill","Crash Ending Fill"],bars:1},
  ]},
 {name:"Funk Workout",bpm:100,desc:"Two funk grooves traded with fills. Builds pocket and chops.",
  parts:[
   {label:"Groove A",ref:["groove","Money Beat (Funk)"],bars:4},
   {label:"Fill",ref:["fill","Linear Funk Fill"],bars:1},
   {label:"Groove B",ref:["groove","Funky Drummer"],bars:4},
   {label:"Fill",ref:["fill","Half-Bar Tom Fill"],bars:1},
  ]},
 {name:"Shuffle Blues",bpm:96,desc:"Shuffle feel with triplet fills.",
  parts:[
   {label:"Shuffle",ref:["groove","Shuffle (Triplet)"],bars:4},
   {label:"Fill",ref:["fill","Triplet Tom Fill"],bars:1},
   {label:"Slow Blues",ref:["groove","12/8 Blues"],bars:4},
   {label:"Fill",ref:["fill","Triplet Tom Fill"],bars:1},
  ]},
 {name:"Pop Set",bpm:108,desc:"Verse/chorus pop dynamics with clean fills.",
  parts:[
   {label:"Verse",ref:["groove","Pop Groove"],bars:4},
   {label:"Fill",ref:["fill","Two-Beat Build"],bars:1},
   {label:"Chorus",ref:["groove","Motown Backbeat"],bars:4},
   {label:"Fill",ref:["fill","Basic 4-Beat Fill"],bars:1},
  ]},
];

/* ===== COURSE — a progressive curriculum =====
   Each lesson: {title, goal, focus, tips:[], bpm, target, ref:[sec,name] OR pattern:{...}} */
const COURSE=[
 {level:"Level 1 · Foundations", lessons:[
  {title:"Meet the Kit & Counting", goal:"Play steady quarter notes on the hi-hat while counting 1-2-3-4 out loud.",
   focus:"Before anything else, internalize the pulse. Tap your foot, count aloud, and let every hi-hat note line up exactly with the metronome click.",
   tips:["Sit up straight, relax your shoulders","Hold the sticks loosely — let them rebound","Count OUT LOUD, every single bar"],
   bpm:70,target:100,sub:4,
   pattern:{name:"Quarter-Note Pulse",style:"Lesson",meter:"4/4",sub:4,tracks:{hat:"x...x...x...x..."}}},
  {title:"The Backbeat", goal:"Add the snare on beats 2 & 4 under quarter-note hats.",
   focus:"The backbeat is the soul of popular music. Make beats 2 & 4 strong and confident — that's where the head nods.",
   tips:["Snare hits should be louder than the hats","Keep the hi-hat perfectly even","Feel '1-TWO-3-FOUR'"],
   bpm:70,target:100,sub:4,
   pattern:{name:"Backbeat Builder",style:"Lesson",meter:"4/4",sub:4,tracks:{hat:"x...x...x...x...",snare:"....x.......x..."}}},
  {title:"Your First Beat", goal:"Combine hi-hat 8ths, kick on 1 & 3, snare on 2 & 4 — the basic rock beat.",
   focus:"This is THE beat. Slow it right down until all three limbs lock together, then nudge the tempo up.",
   tips:["Start at 70 and only speed up when it's clean","Kick and snare should never sound rushed","Use the Speed Trainer to climb gradually"],
   bpm:70,target:110,ref:["groove","Basic Rock Beat"]},
  {title:"Even Hands: Single Stroke Roll", goal:"Play smooth, even single strokes (R L R L) at a steady tempo.",
   focus:"Great drumming starts with even hands. Record yourself — can you hear which hand is which? You shouldn't be able to.",
   tips:["Match your weak hand to your strong hand","Keep stick heights equal","Relax — speed comes from looseness, not force"],
   bpm:75,target:120,ref:["rudiment","Single Stroke Roll"]},
 ]},
 {level:"Level 2 · Rock Grooves", lessons:[
  {title:"8th-Note Kick Variations", goal:"Add a syncopated kick on the '&' of 2.",
   focus:"Moving the kick off the downbeat is your first taste of groove. Keep the hats and snare rock-solid while the kick dances.",
   tips:["Don't let the snare move with the kick","Subdivide '1 & 2 & 3 & 4 &' aloud"],
   bpm:80,target:120,ref:["groove","Rock w/ 8th Kicks"]},
  {title:"Your First Fill", goal:"Play a basic 16th-note tom fill and return to the groove cleanly.",
   focus:"A fill is just decoration that lands you back on beat 1. The hardest part is the re-entry — practice the bar AFTER the fill too.",
   tips:["Count through the fill: 1e&a 2e&a...","End on the floor tom, crash on the next '1'","Don't speed up during the fill"],
   bpm:80,target:110,ref:["fill","Basic 4-Beat Fill"]},
  {title:"Double Stroke Roll", goal:"Develop controlled doubles (R R L L) using rebound.",
   focus:"Let the stick bounce for the second hit instead of playing two separate strokes. This unlocks speed and rolls.",
   tips:["Two equal notes per hand","Use a relaxed fulcrum (thumb + index)","Slow practice builds fast doubles"],
   bpm:65,target:110,ref:["rudiment","Double Stroke Roll"]},
  {title:"Crash & Dynamics", goal:"Open up the groove with a crash on beat 1 and louder backbeats.",
   focus:"Dynamics turn a beat into music. Try the groove quietly, then loud, then crash beat 1 of every other bar.",
   tips:["Crash with the kick on '1'","Let some bars breathe softer"],
   bpm:90,target:120,ref:["groove","Four-on-the-Floor"]},
 ]},
 {level:"Level 3 · Funk & Dynamics", lessons:[
  {title:"Ghost Notes", goal:"Add whisper-quiet ghost notes around a funk backbeat.",
   focus:"Ghost notes are the secret of funk. They're barely audible — almost felt more than heard. Keep them tiny and let the accents pop.",
   tips:["Ghosts at ~10% volume, accents at 100%","Keep the wrist low for ghosts","Listen to the contrast"],
   bpm:80,target:105,ref:["groove","Money Beat (Funk)"]},
  {title:"16th-Note Hi-Hats", goal:"Ride continuous 16th notes on the hi-hat under a backbeat.",
   focus:"This busier hand pattern is everywhere in funk and pop. If your single hand tires, alternate hands on the hats.",
   tips:["Keep 16ths even and quiet","Accent the downbeats lightly"],
   bpm:80,target:110,ref:["groove","16th Hi-Hat Funk"]},
  {title:"Single Paradiddle", goal:"Play paradiddles (RLRR LRLL) with an accent on each first note.",
   focus:"The paradiddle is the gateway to coordination and around-the-kit fills. The accent makes it musical.",
   tips:["Accent only the first of each group","Once smooth, move the accented hand to a tom"],
   bpm:80,target:120,ref:["rudiment","Single Paradiddle"]},
  {title:"Linear Funk Fill", goal:"Play a linear fill where no two limbs hit at once.",
   focus:"Linear playing weaves kick, snare and toms into a single stream of notes. Say the limb order out loud before you play it.",
   tips:["One note at a time — no stacking","Start very slow"],
   bpm:80,target:110,ref:["fill","Linear Funk Fill"]},
 ]},
 {level:"Level 4 · Feel & Triplets", lessons:[
  {title:"The Shuffle", goal:"Play a triplet-based shuffle feel.",
   focus:"Swap straight 8ths for a triplet bounce. Say 'tri-pl-et' and play on 'tri' and 'et'. This feel powers blues, rock and jazz.",
   tips:["Skip the middle of each triplet","Keep the snare backbeat strong"],
   bpm:85,target:120,ref:["groove","Shuffle (Triplet)"]},
  {title:"Triplet Fills", goal:"Play smooth triplet fills around the toms.",
   focus:"Triplet fills feel different from 16ths — rounder and rolling. Keep all three notes of each triplet perfectly even.",
   tips:["Count '1-trip-let, 2-trip-let'","Move down the toms evenly"],
   bpm:85,target:120,ref:["fill","Triplet Tom Fill"]},
  {title:"Jazz Swing Ride", goal:"Play the swing ride pattern with hi-hat foot on 2 & 4.",
   focus:"The spang-a-lang ride pattern is the foundation of jazz. Get the ride and hi-hat foot locked before adding hands/feet comping.",
   tips:["Ride: 'ding, ding-da-ding'","Crisp hi-hat foot chick on 2 & 4"],
   bpm:100,target:160,ref:["groove","Jazz Swing"]},
  {title:"Paradiddles Around the Kit", goal:"Orchestrate paradiddles between snare and toms.",
   focus:"Take the paradiddle you learned and move the accented note to a tom. Suddenly a rudiment becomes a melodic fill.",
   tips:["Accent hand on toms, other on snare","Keep the sticking strict"],
   bpm:85,target:120,ref:["rudiment","Single Paradiddle"]},
 ]},
 {level:"Level 5 · Independence & Styles", lessons:[
  {title:"The Half-Time Shuffle", goal:"Attempt the ghosted half-time shuffle (the 'Rosanna' feel).",
   focus:"A masterclass groove. Layer quiet triplet ghost notes around a big backbeat on 3. Take it extremely slowly.",
   tips:["Big snare on 3, everything else ghosted","This takes weeks — be patient"],
   bpm:70,target:96,ref:["groove","Half-Time Shuffle"]},
  {title:"Bossa Nova", goal:"Play the bossa cross-stick clave over a steady kick.",
   focus:"Independence between a repeating clave (cross-stick), steady hats, and a soft constant kick. The cornerstone of Latin drumming.",
   tips:["Cross-stick stays relaxed","Kick should be felt, not heard"],
   bpm:100,target:140,ref:["groove","Bossa Nova"]},
  {title:"Putting It Together", goal:"Play a full song: grooves and fills in an arrangement.",
   focus:"Use Song Mode. The goal is musicality: smooth transitions, fills that land, and consistent tempo from start to finish.",
   tips:["Don't rush the fills","Keep the same tempo the whole way through","Record it and listen back"],
   bpm:112,target:130,song:"Rock Anthem"},
 ]},
];
